### ISSUE TITLE
Google import location crash

### ISSUE THREAD

**Issue by justinklchan** [covidsafe/App-iOS#104] opened 2020-05-06 01:46 UTC
I tried to import my location and it crashed after entering my google credentials.
I know that my kml file is empty and I don't have a location history, possibly this is causing a crash?

**Comment by ApolloZhu** [comment] 2020-05-06 02:43
My location history is also empty and it didn't crash. Could you please share some console output, or maybe which line of code did it crash on?

**Comment by justinklchan** [comment] 2020-05-06 04:31
Hmm... I didn't download the code. But I tried a few times just now after restarting the app, and it seems to have crashed. Maybe the version on TestFlight is out of date?

**Comment by ApolloZhu** [comment] 2020-05-06 04:50
What do you mean by crash? There was fix #92 (on unhandled promise rejection) but it shouldn't be/wasn't fatal (at least in debug mode).

**Comment by justinklchan** [comment] 2020-05-06 04:55
https://youtu.be/9cJryCqEN54

**Comment by ApolloZhu** [comment] 2020-05-06 05:02
Until maybe Cheng could give me the crash log from their account, could you please share the crash log? You can follow [these instructions](https://help.getpocket.com/article/1098-how-to-find-the-iphone-ipad-app-crash-logs) and look for covidsafe, or try to compile from source and see if the issue is still there.

**Comment by cheng-tan** [comment] 2020-05-06 15:33
@justinklchan we weren't able to find the crash report for this one. Can you share the crash log with @ApolloZhu to help us debug this issue?

**Comment by ApolloZhu** [comment] 2020-05-12 07:46
This should have been fixed by #124

**Comment by kumpera** [comment] 2020-05-12 14:27
We had a lot of recent crashes on import, the crash is fixed but the underlying issue triggering it, some sort of parsing issue, still lingering and we need to collect data on it.

This will be covered by #125

**Closed as completed** 2020-05-12 14:27 UTC
Labels: crash - high priority
