### ISSUE TITLE
Improve Date Formatting

### ISSUE THREAD

**Issue by ApolloZhu** [covidsafe/App-iOS#79] opened 2020-05-02 05:22 UTC
So today is May **2***nd*. However, the DateConverter somehow got **02**, and *nd* capitalized:

![80855871-e48d8000-8c12-11ea-8372-76a0dcc2d94d](https://user-images.githubusercontent.com/10842684/80856163-739b9780-8c15-11ea-9264-0b54db32b55b.png)

**Comment by ApolloZhu** [comment] 2020-05-02 05:38
Though we could fix our own DateConverter, I would like to propose moving this task to native side where DateFormatter respects user’s other preferences like locale, time formatting style (e.g. military time instead AM/PM) , and more

**Comment by cheng-tan** [comment] 2020-07-16 15:17
AM/PM is by design, closing this issue for now.

**Closed as completed by cheng-tan** 2020-07-16 15:17 UTC
